car_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index_view),
    path('cars/', include("cars.urls")),
    path('admin/', admin.site.urls)
]

cars/urls.py
from django.urls import path
from . import views

app_name = "cars"

urlpatterns = [
    path("list/", views.list_view, name="list-cars"),
    path("add/", views.add_view, name="add-cars"),
    path("delete/", views.delete_view, name="delete-cars")
]

cars/models.py
from django.db import models

# Create your models here.

class Car(models.Model):
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f"Car is {self.brand} {self.year}"

car_site/views.py
from django.shortcuts import render

def index_view(request):
    return render(request, "car_site/index.html")

cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models
# Create your views here.

def list_view(request):
    cars = models.Car.objects.all()
    return render(request, "cars/list.html", context={"cars": cars})


def add_view(request):
    if request.POST:
        brand = request.POST["brand"]
        year = int(request.POST["year"])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse("cars:list-cars"))
    else:
        return render(request, "cars/add.html")

def delete_view(request):
    if request.POST:
        pk = request.POST["pk"]
        try:
            models.Car.objects.get(pk=pk).delete()
        except:
            print("PK not found")
        return redirect(reverse("cars:list-cars"))
    else:
        return render(request, "cars/delete.html")

cars/templates/cars/add.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1> ADD.HTML </h1>
    <form action="" method="POST" >
        {% csrf_token %}
        <div class="mb-3">
          <label for="brand" class="form-label">Brand</label>
          <input type="text" class="form-control" id="brand" name="brand">
        </div>
        <div class="mb-3">
          <label for="year" class="form-label">Year</label>
          <input type="text" class="form-control" id="year" name="year">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
{% endblock content %}

cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1> DELETE.HTML </h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="pk" class="form-label">Brand</label>
            <input type="text" class="form-control" id="pk" name="pk">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </form>
</div>
{% endblock content %}

cars/templates/cars/list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1> LIST.HTML </h1>
    <ul>
        {% for car in cars %}
            <li>{{car}}</li>
        {% endfor %}
    </ul>
    
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href={% url "cars:list-cars" %}>List</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href={% url "cars:add-cars" %}>Add</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href={% url "cars:delete-cars" %}>Delete</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        {% block content %}
        {% endblock content %}
        
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

templates/car_site/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to Django Car Site</h1>
{% endblock content %}